### ISSUE TITLE
`changes` method fails with 404 error code

### ISSUE THREAD

**Issue by franc0is** [Simperium/simperium-python#9]
Calling it from the python REPL returns a 404, and attempts at querying it with cURL do as well. Has the endpoint been removed from the server?

This is vexing as there are no other ways for a non-admin user to sync changes across clients via HTTP.

```
(ins)>>> from simperium.core import Auth, Api
(ins)>>> auth = Auth('xxx, 'xxx')
(ins)>>> token = auth.authorize('xxx', 'xxx')
(ins)>>> api.todo.index()
{u'current': u'5a92faf5d9b5bb1d2d05a3b6', u'index': [{u'id': u'91faf5558dc8cb57c367', u'v': 3}]}
(ins)>>> api.todo.changes()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "simperium/core.py", line 282, in changes
    response = self._request(url, headers=headers, timeout=timeout)
  File "simperium/core.py", line 120, in _request
    response = urllib2.urlopen(request, timeout=timeout)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by franc0is** [comment]
Also related: https://github.com/Simperium/simperium-python/issues/2

**Comment by roundhill** [comment]
Try passing it a cv, so using the one from your example:

```
api.todo.changes(cv='5a92faf5d9b5bb1d2d05a3b6')
```

You should see the next change fire after the `todo` bucket updates for that user.

**Comment by franc0is** [comment]
Thanks @roundhill, that did the trick. I got something working in https://github.com/franc0is/simperium-c/commit/3d6e27dcbd1b1669cd80878044e310050621db5a
